In [18]:
import numpy as np

a = np.array([[1, 2, 3]]) #.reshape(3, 1)
b = np.array([[4], [5], [6]])

result = np.matmul(b, a)  # Matrix multiplication

print(a)
print(a.reshape(1, 3))
print(b)
print(result)

[[1 2 3]]
[[1 2 3]]
[[4]
 [5]
 [6]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
